#[cfg(feature = "ssr")]
pub mod config;
pub mod contract;
#[cfg(feature = "ssr")]
pub mod db;
#[cfg(feature = "ssr")]
pub mod dependency;
pub mod domain;
pub mod dto;
#[cfg(feature = "ssr")]
pub mod repository;
#[cfg(feature = "ssr")]
pub mod rest;
#[cfg(feature = "ssr")]
pub mod server;
#[cfg(feature = "ssr")]
pub mod service;
#[cfg(feature = "ssr")]
pub mod state;
pub mod telemetry;
pub mod web;
